const position = { x: 0, y: 0 };

export const mindmapData = {
    nodes: [
        { id: '1', data: { label: 'Benefit Options' }, position},
        { id: '2', data: { label: 'Northwind Health Plus' }, position},
        { id: '3', data: { label: 'Northwind Standard' }, position },
        { id: '4', data: { label: 'Medical Services' }, position },
        { id: '5', data: { label: 'Hospital Stays' }, position },
        { id: '6', data: { label: 'Doctor Visits' }, position },
        { id: '7', data: { label: 'Lab Tests and X-rays' }, position },
        { id: '8', data: { label: 'Emergency Services' }, position },
        { id: '9', data: { label: 'In-Network Emergency Services' }, position},
        { id: '10', data: { label: 'Out-of-Network Emergency Services' }, position },
        { id: '11', data: { label: 'Prescription Drug Coverage' }, position },
        { id: '12', data: { label: 'Generic and Brand-Name Drugs' }, position },
        { id: '13', data: { label: 'Specialty Drugs' }, position },
        { id: '14', data: { label: 'Mental Health and Substance Abuse Coverage' }, position },
        { id: '15', data: { label: 'Vision and Dental Services' }, position},
        { id: '16', data: { label: 'Tips for Coordinating Benefits' }, position },
        { id: '17', data: { label: 'COB Definitions' }, position },
        { id: '18', data: { label: 'Tips for Employees' }, position },
        { id: '19', data: { label: 'Coverage for Hospice Care' }, position }
      ],
      edges: [
        { id: 'e1-2', source: '1', target: '2' },
        { id: 'e1-3', source: '1', target: '3' },
        { id: 'e2-4', source: '2', target: '4' },
        { id: 'e4-5', source: '4', target: '5' },
        { id: 'e4-6', source: '4', target: '6' },
        { id: 'e4-7', source: '4', target: '7' },
        { id: 'e2-8', source: '2', target: '8' },
        { id: 'e8-9', source: '8', target: '9' },
        { id: 'e8-10', source: '8', target: '10' },
        { id: 'e2-11', source: '2', target: '11' },
        { id: 'e11-12', source: '11', target: '12' },
        { id: 'e11-13', source: '11', target: '13' },
        { id: 'e2-14', source: '2', target: '14' },
        { id: 'e2-15', source: '2', target: '15' },
        { id: 'e3-16', source: '3', target: '16' },
        { id: 'e3-17', source: '3', target: '17' },
        { id: 'e3-18', source: '3', target: '18' },
        { id: 'e3-19', source: '3', target: '19' }
      ]
}

export const dynamicData = {
    nodes: [
      { id: 1, data: { label: 'Benefit Options' }, position: { x: 0, y: 0 } },
      { id: 2, data: { label: 'Northwind Health Plus' }, parent: 1 },
      { id: 3, data: { label: 'Northwind Standard' }, parent: 1 },
      { id: 4, data: { label: 'Medical Services' }, parent: 2 },
      { id: 5, data: { label: 'Hospital Stays' }, parent: 4 },
      { id: 6, data: { label: 'Doctor Visits' }, parent: 4 },
      { id: 7, data: { label: 'Lab Tests and X-rays' }, parent: 4 },
      { id: 8, data: { label: 'Emergency Services' }, parent: 2 },
      { id: 9, data: { label: 'In-Network Emergency Services' }, parent: 8 },
      { id: 10, data: { label: 'Out-of-Network Emergency Services' }, parent: 8 },
      { id: 11, data: { label: 'Prescription Drug Coverage' }, parent: 2 },
      { id: 12, data: { label: 'Generic and Brand-Name Drugs' }, parent: 11 },
      { id: 13, data: { label: 'Specialty Drugs' }, parent: 11 },
      { id: 14, data: { label: 'Mental Health and Substance Abuse Coverage' }, parent: 2 },
      { id: 15, data: { label: 'Vision and Dental Services' }, parent: 2 },
      { id: 16, data: { label: 'Tips for Coordinating Benefits' }, parent: 3 },
      { id: 17, data: { label: 'COB Definitions' }, parent: 3 },
      { id: 18, data: { label: 'Tips for Employees' }, parent: 3 },
      { id: 19, data: { label: 'Coverage for Hospice Care' }, parent: 3 },
    ],

    edges: [
      { id: '1-2', source: '1', target: '2' },
      { id: '1-3', source: '1', target: '3' },
      { id: '2-4', source: '2', target: '4' },
      { id: '4-5', source: '4', target: '5' },
      { id: '4-6', source: '4', target: '6' },
      { id: '4-7', source: '4', target: '7' },
      { id: '2-8', source: '2', target: '8' },
      { id: '8-9', source: '8', target: '9' },
      { id: '8-10', source: '8', target: '10' },
      { id: '2-11', source: '2', target: '11' },
      { id: '11-12', source: '11', target: '12' },
      { id: '11-13', source: '11', target: '13' },
      { id: '2-14', source: '2', target: '14' },
      { id: '2-15', source: '2', target: '15' },
      { id: '3-16', source: '3', target: '16' },
      { id: '3-17', source: '3', target: '17' },
      { id: '3-18', source: '3', target: '18' },
      { id: '3-19', source: '3', target: '19' },
    ],
};